version: '2'
services:

    ghost-buster:
        image: umputun/ghost-buster-docker
        build: build/ghost-buster
        restart: always
        container_name: ghost-buster

        environment:
            - BLOG_DOMAIN=http://${BLOG_DOMAIN}
            - NODE_ENV=production
            - TZ=${TIME_ZONE}

        ports:
            - "2368:2368"
        volumes:
            - ./static:/ghost/static
            - ./data:/ghost-override
            - ./export.md:/export.md

    nginx:
        build: build/nginx
        restart: always
        container_name: ghost-nginx

        depends_on:
            - ghost-buster

        ports:
            - "80:80"
            - "443:443"

        volumes:
            - ./etc/ssl:/etc/nginx/ssl
            - ./static:/ghost/static
            - ./logs:/var/log/nginx

        environment:
            - LETSENCRYPT=true
            - TZ=${TIME_ZONE}
            - LE_EMAIL=${EMAIL}
            - LE_FQDN=${BLOG_DOMAIN}
            #- SSL_CERT=le-crt.pem
            #- SSL_KEY=le-key.pem
